#+Title: Apostila Inov Tec

* Revis Bibliográfica: Inovação
  http://pedrotrillo.com/wp-content/uploads/2016/01/Whatisdisruptiveinnovation.pdf
  


  https://www.sciencedirect.com/science/article/pii/S0959652613005751


* Revis Bibliográfica: Empreendedorismo e Inovação


* Revis Bibliográfica: Inovação na Saúde
  http://www.scielo.br/scielo.php?pid=S0102-311X2016001400101&script=sci_arttext&tlng=pt
  https://www.ghdonline.org/uploads/Health_IT_Innovation.pdf


* Revis Bibliográfica: Teoria Inovação 


* Organismos Importantes
** Internacionais
*** Nações Unidas
    https://news.un.org/pt/
    
    
*** Organização para a Cooperação e Desenvolvimento Económico  
    http://www.oecd.org/
    https://pt.wikipedia.org/wiki/Organiza%C3%A7%C3%A3o_para_a_Coopera%C3%A7%C3%A3o_e_Desenvolvimento_Econ%C3%B3mico
*** UNESCO
    https://en.unesco.org/
    https://en.wikipedia.org/wiki/UNESCO
*** Comissão Econômica para a América Latina e o Caribe
    https://www.cepal.org/pt-br
    https://pt.wikipedia.org/wiki/Comiss%C3%A3o_Econ%C3%B4mica_para_a_Am%C3%A9rica_Latina_e_o_Caribe
    https://www.cepal.org/pt-br/subscription (nao tem feed)
** Nacionais
*** Ministério da Saúde - DATASUS
    http://portalms.saude.gov.br/
    http://www2.datasus.gov.br/DATASUS/index.php
    
*** Nic.br
    https://www.nic.br/
    https://en.wikipedia.org/wiki/NIC.br
    Responsável pela operação do domínio br 
    Informações relevantes sobre o funcionamento da internet no brasil
*** Comitê Gestor da Internet no Brasil
    The purpose of the agency is to promote technical quality, innovation and the dissemination of Internet services in Brazil.
    https://en.wikipedia.org/wiki/Comit%C3%AA_Gestor_da_Internet_no_Brasil
    https://pt.wikipedia.org/wiki/Comit%C3%AA_Gestor_da_Internet_no_Brasil
    Núcleo de Informação e Coordenação do Ponto BR
    https://pt.wikipedia.org/wiki/N%C3%BAcleo_de_Informa%C3%A7%C3%A3o_e_Coordena%C3%A7%C3%A3o_do_Ponto_BR

*** Conselho Nacional de Secretários Estaduais para Assuntos de CT&I
    http://www.consecti.org.br/
    Fórum Global de Inovação e Tecnologia em Sustentabilidade    (http://www.consecti.org.br/evento/futurecom/)


* Dimensões da qualidade da informação
https://repositorium.sdum.uminho.pt/bitstream/1822/2183/1/O%20papel%20da%20qualidade%20da%20informacao%20nos%20sistemas%20de%20informacao%20-%20completo.pdf
Intrínseca: Características intrínsecas dos dados, independentes da sua aplicação
Contextual: Características dependentes do contexto de utilização dos dados
Representacional: Características derivadas da forma como a informação é apresentada
Acessibilidade: Aspectos relativos ao acesso e à segurança dos dados
http://www.scielo.br/pdf/tinf/v20n1/03.pdf


* Decisões comuns em TI
** Qual tecnologia adotar?
** Qual futuro desta tecnologia?
** Qual provedor de tecnologia contratar?


* Como se manter atualizado  
  Tem que obter informação de qualidade certo? As dimenções de
qualidade da informação são relevantes neste caso.
  
** Obter informacoes Instanteneamente
*** Feeds
    https://en.wikipedia.org/wiki/RSS

**** Uma Listagem de bons Leitores de feeds
     https://www.tecmint.com/best-rss-feed-readers-for-linux/
     https://www.slant.co/topics/7710/~rss-readers-for-windows
     https://techwayz.com/best-free-windows-10-rss-feed-reader-software/
     https://www.tecmint.com/best-rss-feed-readers-for-linux/
*** Sugestao   
    https://en.wikipedia.org/wiki/Feedly
   
**** Email Letters 
**** Twitter   
**** Redes Sociais
     O Problema de usar o facebook, por exemplo, é que a gente pode dispersar.

** Estudando Material de Pesquisa
*** TIC Saúde
  https://cetic.br/pesquisa/saude/
  Realizada desde 2013
  https://cetic.br/media/docs/publicacoes/2/tic_saude_2017_livro_eletronico.pdf
**** Informações sobre: 
**** Infraestrutura
**** Disponibilidade das TIC
     Estágios de Adoção
     Registro eletrônico e Troca de Informações
     Telessaúde
**** Aplicações nos estabelecimentos de saúde
**** Utilização das TICS dos profisionais de saúde 
     Perfil dos profisisonais
   
**** Principais barreiras para utilização das TICs
*** Gartner
    É uma pesquisa relativa a posição competitiva dos principais
    provedore de tecnologia em mercados de rápido crescimento. Os
    provedores são posicionados em relação aos conceitos de Lider de
    Mercado, Visionários, Com foco em nicho de emrcado e Desafiadores.
    Esse link abaixo lista os mercados...
    
    The following list of markets, dates and research documents is updated throughout the year with the latest Magic Quadrant and Critical Capabilities research notes. View upcoming research on the Publication Calendar.
    https://www.gartner.com/en/research/magic-quadrant
    
*** Publicações WHO 
    https://www.who.int/publications/en/
    https://www.who.int/gho/publications/world_health_statistics/en/
    http://apps.who.int/iris/
    http://apps.who.int/bookorders/anglais/libraries_dep1.jsp?codpay=BRA&libpay=BRAZIL&typbib=K07D
    https://www.who.int/gho/publications/en/
    https://www.who.int/news-room/fact-sheets/detail/elder-abuse
    https://www.who.int/whr/en/
    https://www.who.int/healthinfo/en/
    http://apps.who.int/iris/bitstream/handle/10665/272596/9789241565585-eng.pdf
**** World health statistics 2018: monitoring health for the SDGs, sustainable development goals
     http://apps.who.int/iris/bitstream/handle/10665/272596/9789241565585-eng.pdf

**** WHO Library Cataloguing-in-Publication     
     Data Global health risks: mortality and burden of disease attributable to selected major risks.
     Health in 2015: from MDGs, Millennium Development Goals to SDGs, Sustainable Development Goals.
     http://apps.who.int/iris/bitstream/handle/10665/200009/9789241565110_eng.pdf?sequence=1
     
*** Publicações do DATASUS (Cadernos de Informação de Saúde)
    http://tabnet.datasus.gov.br/tabdata/cadernos/cadernosmap.htm
        
** Obtendo dados para análise
*** Global Health Observatory (GHO) data 
    https://www.who.int/gho/publications/world_health_statistics/en/
    

   http://www2.datasus.gov.br/DATASUS/index.php?area=02
   
*** Dados do Datasus
    https://www.youtube.com/watch?v=S--kEZQOLn8
    http://datasus.saude.gov.br/

** Estudando a literatura (Bases Bibliográficas)
   https://www.ncbi.nlm.nih.gov/search/all/?term=innovation
   Produção científica em saúde pública e as bases bibliográficas internacionais
   https://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0102-311X1999000400022
   https://www.nesc.ufg.br/up/19/o/Produ____o_cient__fica_em_sa__de_p__blica_e_as_bases_bibliogr__ficas_internacionais.pdf
   https://www.researchgate.net/publication/26359300_Producao_cientifica_em_saude_publica_e_as_bases_bibliograficas_internacionais
   https://www.unasus.unifesp.br/biblioteca_virtual/esf/1/modulo_cientifico/Unidade_13.pdf
   Bases bibliográficas para consultas
   https://bibsaude.files.wordpress.com/2012/05/bases-de-dados-da-saude.pdf
   http://saudepublica.bvs.br/vhl/literatura-cientifica-e-tecnica/bases-bibliograficas/
   
** Canais do youtube
   https://www.youtube.com/channel/UCeVBe0AGRmxJ1mN7hS8m-ow
   https://www.youtube.com/channel/UCfZlrtqmgmf8c06PtWf2m3g
   https://www.youtube.com/channel/UCBUDLhhe-Mp8QDTt1Ba3LMA
   https://www.youtube.com/channel/UChyx-6aVOvoKY_l0TF8jTCg
   https://www.youtube.com/channel/UCVAcIPEoCeuaDYICLJzpRSw
   https://www.youtube.com/channel/UC61qCC3gN6IDfIRkIKOqjIA
   http://himsstv.brightcovegallery.com/

** Cursos
   https://www.edx.org/course/creating-sustaining-innovation-culture-uqx-corpinn4x?utm_source=sailthru&utm_medium=email&utm_campaign=newsletter_themed_20181204

* Sistemas de Saúde No Mundo
  https://www.commonwealthfund.org/publications/fund-reports/2014/jun/mirror-mirror-wall-2014-update-how-us-health-care-system?redirect_source=/publications/fund-reports/2014/jun/mirror-mirror
  https://www.thelocal.de/20100510/27107
  https://www.theatlantic.com/health/archive/2014/05/the-struggle-for-universal-healthcare/361854/
  
** inovação nos Sistemas de Saúde No Mundo
   https://www.rand.org/content/dam/rand/pubs/research_reports/RR1100/RR1143/RAND_RR1143.pdf


* SUS - Sistema Único de Saúde
  https://en.wikipedia.org/wiki/Sistema_%C3%9Anico_de_Sa%C3%BAde
  https://pt.wikipedia.org/wiki/Sistema_%C3%9Anico_de_Sa%C3%BAde
  http://portalms.saude.gov.br/sistema-unico-de-saude
  http://tabnet.datasus.gov.br/tabdata/cadernos/sp.htm
** Sistemas
   http://cartaonet.datasus.gov.br/
   http://cartaonet.datasus.gov.br/downloadsNovo.asp
   http://cns.saude.ce.gov.br/downloads/dados/instala%C3%A7%C3%A3o_simplificado_flash.swf
   
*** SNA - Sistema Nacional de Auditoria
    http://sna.saude.gov.br/publicacoes.cfm
   
INTEGRADOR
Pacto de Atenção Básica 2006
SIAB
SIA/SIH
SIOPS
SI-PNI
SISCOLO/SISMAMA
SISPRENATAL


* Modelo de Cuidado nos Sistemas de Saúde
  A Universidade Australiana de Deaking formulou em 2008 para o
"Australian residential aged-care sector" um modelo de cuidado
conhecido com partnership-centred que envolve três pilares fundamentais.

** a partnership-centred approach
   Abordagem centrada no paciente e humanizada
** evidence-based health care
   
** the creation of positive environments.


* Ferramentas de Sofware TI
** Software Livre
   
**  SQL Reporting Services (SSRS)
   server-based report generating software system
   Exemplos:
   https://go.christiansteven.com/-temporary-slug-cb0079ff-56ed-4ae1-b5ba-d84adc19aa61?hs_preview=RTKQUQXw-6700288048&utm_campaign=SQL-RD&utm_content=80863995&utm_medium=social&utm_source=twitter&hss_channel=tw-257500999


* Temas importantes em Informática em Saúde
** 
** CMD
**  Interoperabilidade
   http://datasus.saude.gov.br/interoperabilidade/padroes-e-normas

**  Metodologias 
   http://datasus.saude.gov.br/metodologias/mds-software
   http://datasus.saude.gov.br/metodologias/mgp-projeto
   http://datasus.saude.gov.br/metodologias/mdsoa-projeto
   http://datasus.saude.gov.br/metodologias/mad-metodologia
   http://datasus.saude.gov.br/metodologias/mad-metodologia
   http://datasus.saude.gov.br/metodologias/mgproc-metodologia
   http://datasus.saude.gov.br/metodologias/pgdm-processo-de-gerenciamento-e-desenvolvimento-mobile
** Acesso a Informação  

** value-based care (VBC) e CMS Quality Strategy
   https://www.cms.gov/Medicare/Quality-Initiatives-Patient-Assessment-Instruments/Value-Based-Programs/Value-Based-Programs.html
   https://www.cms.gov/Medicare/Quality-Initiatives-Patient-Assessment-Instruments/Value-Based-Programs/CMS-Quality-Strategy.html
** Referential Matching e Patient Identity Interoperability
   how it can eliminate duplicate medical records
   https://mhealthintelligence.com/resources/white-papers/healthcare-needs-a-new-architecture-for-patient-identity-interoperability?eid=CXTEL000000249793&elqCampaignId=7986&elqTrackId=ba418f3d9b84403598fc725b8f8ea8b1&elq=de702818e9d44202a6def795a37feebd&elqaid=8426&elqat=1&elqCampaignId=7986

** Automação
   
* Assistir esses videos
  https://www.youtube.com/watch?v=URGeSTbPu-Y
  http://cns.saude.ce.gov.br/downloads/dados/instala%C3%A7%C3%A3o_simplificado_flash.swf
  

* sobre startups
** Negócios do tipo matchmakers
  Negócios do tipo "matchmakers": Airbnb, o Bla Bla Car e a
  Eventbrite. "Aplicativos de encontro entre
  "vendedores""[fn:startups_exemplos1]

  A questão da "externalidade de rede" (ou efeito rede) que quer dizer
  que cada usuário que se cadastra agrega valor ao negócio, ou seja,
  "gera um valor extra" aos outros usuários que querem se agregar ao
  negócio. "[fn:startups_exemplos1]

  Pelo fato de lidar tanto com quem quer vender como com quem quer
  adquirir um serviço, essas aplicações são conhecidos como
  "multisided platforms""[fn:startups_exemplos1] É importante manter
  um "equilíbrio".

** exemplos de startups

   
   dockway"[fn:startups_exemplos1]


* Interessantes
  
Lei nº 13.797, de 03/01/19 DOU de 04/01/19 p.3 - seção 1 - nº 3 -
Altera a Lei nº 12.213, de 20 de janeiro de 2010, para autorizar a
pessoa física a realizar doações aos fundos controlados pelos
Conselhos Municipais, Estaduais e Nacional do Idoso diretamente em sua
declaração de Ajuste Anual do Imposto sobre a Renda da Pessoa Física.

Lei nº 13.787, de 27/12/18 DOU de 28/12/18 p.3 - seção 1 - n° 249 -
Dispõe sobre a digitalização e a utilização de sistemas informatizados
para a guarda, o armazenamento e o manuseio de prontuário de paciente.

Medida Provisória nº 869, de 27/12/18 DOU de 28/12/18 p.8 - seção 1 -
n° 249 - Altera a Lei nº 13.709, de 14/08/2018, para dispor sobre a
proteção de dados pessoais e para criar a Autoridade Nacional de
Proteção de Dados, e dá outras providências.

Consulta Pública MS-ANVISA nº 588, de 26/12/18 DOU de 28/12/18 p.421 -
seção 1 - n° 249 - Fica estabelecido o prazo para envio de comentários
e sugestões ao texto da proposta de Resolução da Diretoria Colegiada
(RDC) que define os critérios e os procedimentos para implementação do
gerenciamento informatizado da distribuição de numeração e talonários
de Receituário de Controle Especial no território nacional.

Resolução MS-CNS-600, de 11/10/18 DOU de 14/01/19 p. 66 - seção 1 n°
09 - Aprova o posicionamento brasileiro para a Global Conference on
Primary Health Care, Astana, 2018, anexo a esta resolução.
ftp://ftp.saude.sp.gov.br/ftpsessp/bibliote/informe_eletronico/2019/iels.jan.19/Iels09/U_RS-MS-CNS-600_111018.pdf


Portaria MS-FUNASA nº 125, de 07/01/19 DOU de 11/01/19 p. 47 - seção 1
n° 08 - Designa Coordenador do Projeto e respectivo suplente para
execução do PROJETO DE COOPERAÇÃO TÉCNICA INTERNACIONAL TC-87, firmado
com a Organização Pan-Americana da Saúde - OPAS.
ftp://ftp.saude.sp.gov.br/ftpsessp/bibliote/informe_eletronico/2019/iels.jan.19/Iels08/U_PT-MS-FUNASA-125_070119.pdf





* refs
[fn:startups_exemplos1] https://endeavor.org.br/desenvolvimento-pessoal/enxergando-barreiras-que-nos-impedem-de-crescer/?utm_campaign=news_0701_nao_empreendedores_opt-in&utm_medium=email&utm_source=RD+Station
