* _9. Apresentação e discussão de casos de sucesso de empreendedorismo_

** O empreendedor valoriza pessoas
   Unanimidade: Todos os empreendedores valorizam pessoas. Suas conexões
   não são estratégicas, no sentido de obter vantagem delas, mas são
   estratégicas no sentido de que o relacionamento com as pessoas é matéria
   prima para obter sabedoria e discernimento.
   Em geral citam que é necessário escolher sim com quais pessoas se
   relacionar, quando possível é claro.
   Por exemplo, no vídeo da Dna Maria de Nazaré, ela tem um
   relacionamento com seus pares católicos e com os padres
   também [fn:VideoMariaDeNazare], no vídeo do Carlos, ele demonstra
   grande apreço por pessoas e pelo social e pela
   sustentabilidade[fn:CarlosEngCivil]. Tanto o vídeo do Carlos como do
   Marcelo Sales [fn:VideoDoSilvioSantos] também valorizam a família.

** O projeto do empreendedor é um ingrediente necessário para sua felicidade 
   As pessoas tem mais de um sonho. Não pode ser a única razão pra
   viver. Mas o projeto do empreendendor de sucesso é um dos objetivos/sonhos
   mais importantes que têm. Por isso, toda História de um projeto
   empreendedor se confunde com a  história de vida do próprio
   empreendedor. Ou seja, a história do projeto do empreendedor faz
   parte de suas emoções mais intensas. Quando o empreendedor começa a contar a
   história de seu projeto empreendedor ele mistura a história do projeto
   com sua história de vida. 
   É muito comum o empreendedor chorar [fn:VideoMariaDeNazare][fn:CarlosEngCivil] e demostrar suas emoções porque o
   o seu projeto é algo que envolve suas emoções.
   Emfim, o projeto do emprendedor é mais um ingrediente necessário para
   sua felicidade, para seu processo de realização profissional e pessoal, por isso é comum que no final das palestras e falas
   dos empreendedores eles citem e desejem "felicidade" aos
   ouvintes[fn:VideoDoSilvioSantos] [fn:CarlosEngCivil] .
   
** Nicho de mercado
   Com relação ao mercado, o vídeo da Dna Francisca, o da roupas só
   para padres, é, provavelmente, o exemplo mais interessante para
   compreensão do conceito de nicho de mercado.
   A industria textil têm muitos segmentos, inclusive o religioso, mas
   no caso da Dna Nazaré o segmento é ainda mais delimitado: padres
   católicos.
   Qual a vantagem de trabalhar em um nicho de mercado. Empresas
   grandes e poderosas não conseguem essa capilaridade para
   compreender a atender bem aos padres porque não conseguem ter esse
   relacionamento que a Dona Nazaré tem com eles.
   
   


[fn:VideoMariaDeNazare] https://www.youtube.com/watch?v=JdCwyINYMf0

[fn:VideoMariaDeNazare] vídeo da Dna Francisca (Roupas para Padres)
em http://www.portaleduca.com.br/aluno/cursoConteudo.php?conteudo=7835
acessado em [2017-01-21 Sáb]

[fn:VideoDoSilvioSantos] Vídeo do Silvio santos em
https://www.youtube.com/watch?v=oi706LKU9Rc acessado em [2017-01-21 Sáb]

[fn:CarlosEngCivil] "Day1 | Uma história de empreendedorismo e
sensibilidade - Carlos Terepins [Even]" em
https://www.youtube.com/watch?v=3nLHj7Zcwqg acessado em [2017-01-21 Sáb]

[fn:VideoDoMarceloSalesNerd] Palestra Empreendedorismo - As Conexões que Movem a Vida em
https://www.youtube.com/watch?v=eStNcJ7S7No acessado em [2017-01-21 Sáb]
