
#+Title: Empreendedorismo

* INTRODUÇÃO E PROBLEMATIZAÇÃO
  
  No Brasil e outros estudos no mundo apontam um aumento do número de
  empreendimentos por idosos. Pelo menos duas linhas de raciocínio
  demostram os motivos  [fn:OECD2013](Na Introdução - p1) :
  1) FATORES INSTRINSICAMENTE ECONÔMICOS E SOCIAIS
     Com aumento da expectativa de vida o aumento da idade de
     fundadores de negócios também aumenta. 
     Dentro desse contexto há fatores que "ATRATIVOS", ou seja, que
     facilitam a entrada de idosos em atividades empreendedoras. Neste
     caso são idosos que vêem nesta atividaes mais uma fase em sua
     carreira posto que, neste caso, pode ocorrer maior flexibilidade
     no trabalho e melhor adequação do trabalho a sua qualidade de
     vida. Já os fatores "QUE EMPURRAM" os idosos à atividades
     empreendedoras é a necessidade de continuar trabalhando diante da
     falta de opção no mercado de trabalho[fn:OECD2013](Na Introdução - p1).          
  2) FATORES INTRINSICAMENTE GERONTOLÓGICOS
     Uma ação no sentido de prolongar a vida produtiva, reduzir
     desemprego na terceira idade, propiciar inclusão social, melhorar
     capacidade inovadora através da maturidade dos
     idosos[fn:OECD2013](Na Introdução - p1)
     

  Segundo Veras (2009), as projeções indicam que o país ocupará o  sexto lugar em número  de  idosos  até  2020 [fn:Emp3Idade4TeseMayara](pg.1)
  Aumento do custo de vida devido a gastos com saúde [fn:Emp3Idade4TeseMayara](pg.2)
  Necessidade de ajudar financeiramente filhos e netos [fn:Emp3Idade4TeseMayara](pg.2)
  + Esvaziamento de papéis devido a redução dos contatos sociais [fn:Emp3Idade4TeseMayara](pg.2)
    Em estudos alguns empreendedores idosos apontam como motivo de
    emprender a necessidade de se
    ocupar  [fn:Emp3Idade4TeseMayara](pg.22 e 23 )

  Despreparo do mercado de trabalho para receber o idoso  [fn:Emp3Idade4TeseMayara](pg.2)
  Necessidade de minimizar perdas financeiras decorrente da aposentadoria  [fn:Emp3Idade4TeseMayara](pg.3)
  Muitos não são dependentes, mas sim provedores da família  [fn:Emp3Idade4TeseMayara](pg.3 e 4)


Apesar da relevancia do tema, de sua atualidade e importância, autores
apontam que estudos sobre empreendedorismo na terceira são ainda escassos[fn:ICSB2016](pg.1)


* O empreendedorismo
  O Conceito de Empreendedorismo pode ser considerado relativo a 3 níveis
  de engajamento relativo a atividade empreendedora[fn:OECD2013], conforme metodologia.
  three  engagement  levels:  
  1) Pessoa que nunca pensou em iniciar um negócio próprio.
  2) Pessoa que estava pensando em iniciar um negócio próprio
  3) Pessoa que encontra-se em atividade em um negócio próprio que
     ainda está começando

 ser positivo para 
  Melhoria na qualidade de vida
  Geração de Renda diante do impecílios no mercado de trabalho
  Economia Familiar 
* O empreendedorismo e a 3 Idade
** Contexto
  Trabalhar depois da aposentadoria tem muito mais frequente
  Questões da previdência
** Poder ser bom / Pode ser Ruim
   + BOM  [fn:Emp3Idade4TeseMayara](pg.25)
     fortalece  sua  autoestima,
     aumenta  sua  satisfação, 
     proporciona  a  sensação  de  produtividade,  
     gerar  renda
     manter os grupos de  amizade,  
     independência  financeira,  
     flexibilidade  de  horário  por  serem  proprietários de seu
     empreendimento, o que lhes permite estar presente junto a
     família. 

   + RUIM [fn:Emp3Idade4TeseMayara](pg.25)
     Queixas da  família  devido  ao  excesso  de  trabalho;  
     alta  de  disposição  para  o  lazer  após  o trabalho; 
     Dificuldade de trabalhar tendo problemas crônicos de saúde. 
     A dificuldade de   encontrar   mão   de   obra   comprometida,
     responsável   e   eficiente,
     Dificuldades financeiras, 
** As Barreiras que enfrentam
   + A própria fase da vida: 
     Idosos são menos empreendedores que
     jovens[fn:OECD2013] [fn:ICSB2016](pg.1 segundo paragrafo).
     (pg.2)[fn:OECD2013] (pg.10 Ageism)
   + Dificuldades de suporte financeiro[fn:OECD2013] (pg.8)
      [fn:OECD2013](pg.10 - Resources)
   + Complexidade do processo administrativo do negócio [fn:OECD2013](pg.8) 
     Questões de legislação  [fn:OECD2013](pg.10 - Information and regulations) 
   + Dificuldades em obter informações suficientes sobre como iniciar o negócio[fn:OECD2013] (pg.8)
     Questões de legislação  [fn:OECD2013](pg.10 - Information and regulations) 
   + Dificuldades com círculo social NÃO-Pró-Empreendedorismo
     Pessoas que desanimam ao invés de
     incentivar [fn:OECD2013](pg.10 - Social Environment) 

** Motivo de empreender
*** Gerontologico

    + Esvaziamento de papéis devido a redução dos contatos sociais [fn:Emp3Idade4TeseMayara](pg.2)
      Em estudos alguns empreendedores idosos apontam como motivo de
      emprender a necessidade de se
      ocupar  [fn:Emp3Idade4TeseMayara](pg.22 e 23 )
    + Importancia de se manter ativo  
      Estudos exploratório apontam que "o benefício de se sentir ativo e
      produtivo, supera as dificuldades
      enfrentadas" [fn:Emp3Idade4TeseMayara](pg.30 Paragrafo 7)  
      
*** Por oportunidade
    Há estudos que demonstra haver idosos que iniciam atividades [fn:Emp3Idade4TeseMayara](pg.23)
    empreenndedoras devido a vislumbres de oportunidade 
*** Por necessidade
    Necessidades e/ou demandas financeiras [fn:Emp3Idade4TeseMayara](pg.23)


** Possíveis vantagens Competitivas em relação a empreendedor jovem
  + Senso de realização mais imperativo
  + O idoso tem conhecimento da economia, de mercados, network
  + O trabalho pode ser crucial para a saúde física e emocional[fn:Emp3Idade3Fenacom]. Para muitos que tem um perfil mais ativo.
  + Pode ser importante para saúde financeira e mental l[fn:Emp3Idade3Fenacom].
  + Muitos trabalharam em um ramo de negócio por muitos anos e detém experiência no ramo [fn:OECD2013](p.5) e mais experiência técnica [fn:OECD2013](p.5)  [fn:Emp3Idade4TeseMayara](pg.2). Embora dependendo da região ou contexto isso não é uma  constante  [fn:Emp3Idade4TeseMayara](pg.30 Paragr4).
  + Fazer da aposentadoria um passo positivo no  processo  [fn:Emp3Idade4TeseMayara](pg.4 segundo paragrafo)
  + Ter uma família já estruturada
    Estudos exploratórios apontaram que a relação familiar não foi
    afetada pela atividade
    empreendedora [fn:Emp3Idade4TeseMayara](pg.30 Paragr6)
  + Rede de contatos mais madura e estável (more developed networks)[fn:OECD2013](p.5)
  + Uma situação financeira estável [fn:OECD2013](p.5)

** O que é necessário
   É Necessário: 
   "planejar, ter um plano de vida. Aprender e Reaprender."[fn:Emp3Idade3Fenacom].
   
* notas
  O empreendedorismo pode ser interessante na 3 idade. Instituições
  como sesc de SC[fn:Emp3Idade1] investe nesta idéia.



** perfil  sociodemográfico  do  idoso  empreendedor;   
   Trata-se de idosos jovens com média por volta de 65  anos  [fn:Emp3Idade4TeseMayara](pg.19) 
   Normalmente são pessoas de referência na unidade familiar  [fn:Emp3Idade4TeseMayara](pg20) 
   A renda média mensal foi de 6,6 salários  mínimos  [fn:Emp3Idade4TeseMayara](pg.21 Primeiro Paragrafo) 

** atividades  em que  os  idosos  se  tornaram  empreendedores;  
** idosos  optam  pelo  empreendedorismo  e percepção do idoso sobre motivos pelos quais o significado de permanecer econômica e 
socialmente ativo enquanto empreendedor. 

* Recomendações para Políticas Públicas
  É relevante falar em políticas públicas acerca desse assunto porque
  uma população envelhecida e não ativa pode trazer impactos
  negativos no crescimento econômico e redução da capacidade de
  captação fiscal por parte do governo[fn:ICSB2016] (pg.1-2).
  Além disso autores apontam que esse tipo de mão de obra são
  importantes para o desenvolvimento regional e para economia baseada
  no conhecimento[fn:TingZhang].
  Considerando que o aumento das taxas de empreendedorismo na terceira
  idade é uma realidade...
  + Incentivar/fomentar e promover ações empreendedoras [fn:OECD2013](pg.15)
    Se a intenção de empreender reduz com aumento da
    idade[fn:ICSB2016] (pg.1-2), as ações de incentivo e facilitadoras
    da atividade ganham relevância aumentada. Cabe ressaltar que  
  + Revisar legislação e regulamentações dentro da perspectiva do
    empreend na terceira idade  [fn:OECD2013] (pg.15)
  + Evitar uso excessivo de jargões técnicos em materiais sobre
    empreendedorismo  [fn:OECD2013] (pg.15)
  + Promover ações de conscientização sobre o trabalho na terceira
    idade nas empresas  [fn:OECD2013] (pg.15)
  + Incentivar mentoria na terceira idade [fn:OECD2013] (pg.15)
    
    

* referências

  [fn:Emp3Idade2] https://www.sescsp.org.br/files/edicao_revista/11169179-524a-409a-bf8b-efa2c6e42bd7.pdf
  [fn:Emp3Idade3Fenacom] http://fenacon.org.br/noticias/idosos-e-empreendedores-1003/
  [fn:Emp3Idade4TeseMayara] http://www.locus.ufv.br/bitstream/handle/123456789/8335/texto%20completo.pdf?sequence=1
  [fn:srGarciaDepoimento] https://www.youtube.com/watch?v=19PNbq-fPZ8
  [fn:G1SrGarcia] http://g1.globo.com/educacao/noticia/2014/10/marceneiro-de-86-anos-cria-jogo-para-ensinar-tabuada-criancas.html?TB_iframe=true&width=288&height=432
  [fn:siteMatereeducacional] http://www.matereeducacional.com.br/
  [fn:OECD2013]  https://www.dcu.ie/sites/default/files/agefriendly/senior_bp_final.pdf  (Nota: Considerados a partir de 50 anos)
  [fn:ICSB2016]  http://icsb.org/wp-content/uploads/2016/07/ICSB-Academy-216pdf.pdf  (A partir de 55 anos)
  [fn:TingZhang] https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1470494


