#+TITLE: Gestao da Inovacao Tecnologica

* Apresentacao
  Bem vindo aos interessados em inovação tecnológica.
  Este texto é só um rescunho (por enquanto) e notas de aulas.

  Por enquanto estou me baseando no Livro do Reis[fn:Reis2Ed]
  O primeiro objetivo vou organizar os temas relevantes para discussão
  reflexão sobre o assunto

* A importancia do conhecimento (Sociedade do conhecimento)
  Reis (2008) citando Drucker: Conhecimento não é um recurso para
  inovação, mas o único recurso realmente significativo.p.1
  O poder econômico de uma empresa depende mais das capacidades
  intelectuais de seus recursos humanos que de recursos tangíveis e/ou
  imobilizados.(Reis,2018 p.2)


* Produção do Conhecimento vs Reais Ganhos Econômicos e Sociais do Conhecimento Produzido
  Parece haver um hiato entre produção de conhecimento e a
  transferencia do conhecimento porque  não se transforma esse
  conhecimento em valor econômico.   Reis (2008) releva a questão de que se produz mas em indicadores
  econômicos, como número de patentes, por exemplo, tal procução não
  se confirma p.34 da introdução.
  Possivelmente nem social, embora nao haja um autor ainda que tivesse
  lido que averiguasse isso.



* Mecanismos governamentais de fomento a inovação  

** ministério da ciência, tecnologia, inovações e comunicações
   https://www.google.com/search?safe=active&client=firefox-b&ei=sNH5WrKGCsfywATY0avIDg&q=minist%C3%A9rio+da+ci%C3%AAncia%2C+tecnologia%2C+inova%C3%A7%C3%B5es+e+comunica%C3%A7%C3%B5es&oq=minist&gs_l=psy-ab.3.0.35i39k1j0l9.2730.3378.0.4970.6.6.0.0.0.0.138.600.1j4.5.0....0...1c.1.64.psy-ab..1.5.596...0i131k1.0.m3Uva_9whW8

** Fapesp
   https://www.google.com/search?safe=active&client=firefox-b&ei=JdL5WpWEM4mawgTUtpyIBA&q=fapesp&oq=fapesp&gs_l=psy-ab.3..0l10.46298.47044.0.47458.6.6.0.0.0.0.124.608.4j2.6.0....0...1c.1.64.psy-ab..0.6.606...35i39k1j0i131k1j0i67k1.0.MB8I1cuqpoU

** finep
   https://www.google.com/search?safe=active&client=firefox-b&ei=ZNL5WvC_EIWnwgSZ4JCoBA&q=finep&oq=finep&gs_l=psy-ab.3..0l10.21372.21844.0.22198.5.5.0.0.0.0.102.486.3j2.5.0....0...1c.1.64.psy-ab..0.5.484...35i39k1j0i67k1j0i131k1.0.cokZ6lvJ2KQ

** cnpq
   https://www.google.com/search?safe=active&client=firefox-b&ei=fNL5WqGfDcW7wASshqO4BQ&q=cnpq&oq=cnpq&gs_l=psy-ab.3..0i67k1j0l9.11224.11706.0.12152.4.4.0.0.0.0.98.376.4.4.0....0...1c..64.psy-ab..0.4.376...35i39k1j0i131k1j0i131i67k1.0.q0A54kS_5ig

** sebrae
   https://www.google.com/search?safe=active&client=firefox-b&ei=idL5WonIO4ycwgTcsprgAw&q=sebrae&oq=sebrae&gs_l=psy-ab.3..0j0i131k1j0l8.12968.13850.0.14074.6.4.0.2.2.0.100.382.3j1.4.0....0...1c.1.64.psy-ab..0.6.396...35i39k1j0i67k1.0.x0lOlB5gdso

** iel Instituo Euvaldo Lodi
   https://www.google.com/search?safe=active&client=firefox-b&ei=mdL5WqG9N8SZwQSe27aoBw&q=Instituo+Euvaldo+Lodi&oq=Instituo+Euvaldo+Lodi&gs_l=psy-ab.3..0i13k1l10.23804.23804.0.24252.1.1.0.0.0.0.112.112.0j1.1.0....0...1c.1.64.psy-ab..0.1.112....0.FUOhKmCAaKs

** FVA - Fundo verde e amarelo
   https://acervodigital.ufpr.br/handle/1884/47027
   http://www.mctic.gov.br/mctic/opencms/fundos/fndct/fundos_CeT/ct_verde_amarelo/ct_verde_amarelo.html
   http://www.finep.gov.br/a-finep-externo/fontes-de-recurso/fundos-setoriais/o-que-sao-fundos-setoriais
   http://www.teses.usp.br/teses/disponiveis/96/96132/tde-06052009-092407/pt-br.php

** Política Industrical de Comércio Exterior (PICE)
   https://www.google.com/search?q=Pol%C3%ADtica+Industrical+de+Com%C3%A9rcio+Exterior+%28PICE%29&ie=utf-8&oe=utf-8&client=firefox-b

** Programa Brasileiro de Qualidade e Produtividade (PBPQ)   
   https://www.google.com/search?q=Programa+Brasileiro+de+Qualidade+e+Produtividade+%28PBPQ%29+++&ie=utf-8&oe=utf-8&client=firefox-b

** Programa de Apoio à Capacitação Tecnológica da Indústria (PACTI)   
   https://www.google.com/search?safe=active&client=firefox-b&ei=XtH5WtfMO4yOwgTi4JqgDA&q=Programa+de+Apoio+%C3%A0+Capacita%C3%A7%C3%A3o+Tecnol%C3%B3gica+da+Ind%C3%BAstria+%28PACTI%29&oq=Programa+de+Apoio+%C3%A0+Capacita%C3%A7%C3%A3o+Tecnol%C3%B3gica+da+Ind%C3%BAstria+%28PACTI%29&gs_l=psy-ab.3..0i71k1l8.50666.50666.0.50990.1.1.0.0.0.0.0.0..0.0....0...1c..64.psy-ab..1.0.0....0.SCnDxY6N2zE

** Lei 8661
   https://www.google.com/search?safe=active&client=firefox-b&ei=k9H5WoiuDMGKwgS4pLLwCQ&q=Lei+8661&oq=Lei+8661&gs_l=psy-ab.3..0l2.27882.27882.0.28134.1.1.0.0.0.0.128.128.0j1.1.0....0...1c..64.psy-ab..0.1.128....0.ToJQ3laSWOA

** BNDES
   https://www.google.com/search?safe=active&client=firefox-b&ei=s9L5WvjAIcmewgSPwYfAAg&q=bndes&oq=bndes&gs_l=psy-ab.3..0l10.84498.85482.0.85646.5.4.0.1.1.0.104.398.1j3.4.0....0...1c..64.psy-ab..0.5.404...35i39k1j0i131k1j0i67k1.0._VlY2rw7vl4

** PATME - Programa de Apoio Tecnologico as Micro e Pequenas
   https://www.google.com/search?safe=active&client=firefox-b&ei=ZtP5WpX0OcOYwATBt4noCQ&q=PATME+-+Programa+de+Apoio+Tecnologico+as+Micro+e+Pequenas&oq=PATME+-+Programa+de+Apoio+Tecnologico+as+Micro+e+Pequenas&gs_l=psy-ab.3...9226.9226.0.9492.1.1.0.0.0.0.150.150.0j1.1.0....0...1c..64.psy-ab..0.0.0....0.UKWDqpT5r_I

   


** NIT - Núcleo de Inovação Tecnológica
   http://www.int.gov.br/nucleo-de-inovacao-tecnologica
   http://www3.inpe.br/tec/nit/
   http://sintpq.org.br/index.php/blog/item/3312-os-desafios-dos-nucleos-de-inovacao-tecnologica-nits-no-brasil
   http://inovasaopaulo.org.br/

** SERVIÇOS TÉCNICOS ESPECIALIZADOS  PARA IMPLEMENTAÇÃO DOS NÚCLEOS DE INOVAÇÃO TECNOLÓGICA NOS INSTITUTOS QUE OPERAM NO ÂMBITO DA SECRETARIA DE ESTADO DA SAÚDE
   http://ses.sp.bvs.br/wp-content/uploads/2014/09/relat%C3%B3rio-parcial-2_evolu%C3%A7%C3%A3o-proj.-NITS.pdf
   http://ses.sp.bvs.br/wp-content/uploads/2016/02/Apresentacao-SES-29052014_Ary-Plonski.pdf


* FOOTNOTES
[fn:Reis2Ed] Reis, Dalcio Roberto dos. Gestão da Inovação Tecnologica
2ed Barueri, SP: Manode, 2008.
[fn:isi] Institute of Scientific Information (ISI)
[fn:isi-wikipedia]
https://en.wikipedia.org/wiki/Institute_for_Scientific_Information
[fn:isi-site]
https://www.igi-global.com/dictionary/institute-for-scientific-information-isi/43723
[fn:isi-artigosbrasileiros]
http://www.scielo.br/scielo.php?pid=S0100-19652000000100011&script=sci_arttext&tlng=es

