#+SETUPFILE: ../etc/org_mode_SETUPFILE.org

#+TITLE: CUSTO FUNCIONARIO


* Temas Importantes
** Desoneração da Folha de pagemtno
   "A Contribuição Sindical é devida, por lei, para todas as empresas brasileiras".[fn:fiesp-ccp1]
   
   "_Substituição_ da base de cálculo da contribuição patronal básica de
_20% sobre o total da folha de pagamento de empregados_, trabalhadores
avulsos e contribuintes individuais, a qual pass a a ser calculad
sobre a receita bruta. 
Esta substituição _tem caráter impositivo_ e será aplicada _no período
de 1°. 12.2011 a 31.12. 2014_. Vencido este prazo, a contribuição
previdenciária patronal básica voltará a ser calculada sobre a folha
de pagamento.
   

* Exercícios

** Exercícios - Simples Nacional
(  ) O Simples Nacional é um regime tributário simplificado para micro
pequenas empresas, pois junta 8 tributos (IRPJ, CSLL, PIS/PASEP, Cofins, IPI, ICMS, ISS e CPP) numa única forma de cálculo e pagamento, facilitando a vida das pequenas empresas.

** Exercícios - Diferenças entre MEI e Simples Nacional


** Exercícios MEI - pro-labore [fn:mei-prolab]
   (  ) A legislação trabalhista estabelece um valor mínimo para pro-labore
   (  ) Um pro-labore de 5500 para um MEI é ilegal.
   (  ) Pro-labore para o MEI tem uma função educativa muito importante a
   medida que estabelece uma separação formar entre o oramento pessoal e
   familiar do MEI e de sua empresa
   (  )  

** Exercícios MEI - Recolhimento para o INSS
(  ) 


 Referencias
[fn:mei-prolab] https://blog.contaazul.com/como-calcular-o-pro-labore-mei/

[fn:fiesp-ccp1] http://www.fiesp.com.br/servicos/tabela-guia-contribuicao-sindical/

pdfs
[fn:receita]
http://www8.receita.fazenda.gov.br/simplesnacional/arquivos/manual/manual_pgdas.pdf


 pesquisas
 https://www.google.com.br/search?safe=active&q=holerite+pro+labore+excel&sa=X&ved=0ahUKEwj5h779_sPTAhUFW5AKHT9GDh8Q1QIIXigC&biw=1525&bih=658

 https://www.google.com.br/search?safe=active&q=codigos+de+eventos+para+folha+de+pagamento&sa=X&ved=0ahUKEwiGrp2fgcTTAhUOl5AKHdrkCIYQ1QIIXSgC&biw=1525&bih=658







