#+Title: App Service

* Aplicativo PHP no App Service da Azure

Vamo seguir o tutorial da propria azure.[fn:1]

** clonando um projeto php
Vamos clonar um exemplo de app php, conforme abaixo

#+begin_src sh name: blk1 :exports both  :shebang "#!/usr/bin/bash" :tangle ./projetos/tangle/_1_cloning_project.sh  :mkdirp yes
cd /run/media/administrador/nfts/envdev/PhpProjects/
git clone https://github.com/Azure-Samples/php-docs-hello-world
cd php-docs-hello-world
projdir=$(pwd)
echo $projdir
#+end_src

#+RESULTS:
: /run/media/administrador/nfts/envdev/PhpProjects/php-docs-hello-world

** criando um webapp pra depois enviar nosso codigo pra la
Bom, mas nao rodamos ainda o comando az webapp up --runtime "PHP:8.0" --name myazphpwebapp --os-type=linux

vamos la roda-lo?

#+begin_src sh name: blkname :exports both :shebang "#!/usr/bin/bash" :tangle ./subjectdir/tangle/tangled.sh  :mkdirp yes
  docker run -it  mcr.microsoft.com/azure-cli "az webapp up --runtime PHP:8.0 --resource-group rg_chamadasonline --name webapp_chamadasonline --os-type=linux"
#+end_src

#+RESULTS:

az webapp e um comando com muitas opcoes, vale a pena conhecer-lo melhor[fn:5]




* Repetindo o processo de criacao de aplicativo php no app service do azure

Repeticao e didatica pessoal... vamos apagar o que fizemos e fazer novamente.

A diferenca e que agora vamos criar nosso proprio *plano basico de servico de aplicativo*

E que nao da pra usar a nuvem se falar de dinheiro, vc vai ser cobrado por tudo que vc criar na azure.

Como nos estamos usando a conta de estudante a cobranca sera debitada de seus cretidos

*NAO COLOQUE CARTAO DE CREDITO*

*NAO COLOQUE CARTAO DE CREDITO*

Vc ta comecando agora por isso cuidado com isso, nao coloque cartao de credito.

Como eu tava dizendo nao da pra usar a nuvem sem considerar que vc vai pagar pelo que vc usar.

entao vamos criar um plano basico de servico de aplicativo pra fazer uma configuracao de um plano gratuito de servico de app, o que nao quer dizer que vc nao vai pagar nada, pode que o app seja gratuito mas vc pague por algum outro recurso que seja necessario pra colocar seu app no ar.

Leia com calma quais opcoes e custos existem para os servicos de apps da azure[fn:4]

** Vamos comecar apagando o que tinhamos criado

Excluindo o grupo de recurso que foi criado, excluimos o aplicativo e tudo que foi criado junto. Nao sabe o que e grupo de recurso? Nao fica com essa duvida, pergunte pro prof agora mesmo ele já deveria ter explicado rsrsr

O grupo de recurso que tinha sido criado tinha um nome, temos que pegar o nome dele pra gente exlui-lo

#+begin_src sh name: blkname :exports both  :shebang "#!/usr/bin/bash" :tangle ./subjectdir/tangle/tangled.sh  :mkdirp yes
az group delete --name NomeDoSeuGrupoDeRecurso
#+end_src

Agora tudo que tinhamos feito ja foi apagado entao vamos comecar de novo..



** criando um plano de servico de aplicativo [fn:2] 

Vamos criar primeiro um resource group e depois tudo que a gente criar vai ficar dentro dele.[fn:3]
#+begin_src sh name: blkname :exports both :session s1
  az group create -l westus -n rg_chamadasonline
#+end_src

#+begin_example
mcr.microsoft.com/azure-cli:latest
{
  "id": "/subscriptions/0964e274-8901-424b-9b66-011054aa67e9/resourceGroups/rg_chamadasonline",
  "location": "westus",
  "managedBy": null,
  "name": "rg_chamadasonline",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}
[administrador@fedora shellscript]$ 

#+end_example

Acima vc ve a saida do comando que criou meu grupo de recurso.

Agora vamos criar um appservice plan dentro desse grupo de recurso

#+begin_src sh name: blkname :exports both :shebang "#!/usr/bin/bash" :tangle ./subjectdir/tangle/tangled.sh  :mkdirp yes
az appservice plan create -g rg_chamadasonline --is-linux -n  AppServicePlan_BasicF1 --sku F1
#+end_src


#+begin_src sh name: blkname :exports both :session s1
az webapp create --runtime PHP:8.0 --resource-group rg_chamadasonline --name chamadasonline --plan AppServicePlan_BasicF1 --deployment-local-git
#+end_src


*Parâmetros Exigidos*
--name -n
Nome do novo plano do serviço de aplicativo.

--resource-group -g
Nome do grupo de recursos. Você pode configurar o grupo padrão usando az configure --defaults group=<name>.



*Parâmetros Opcionais*
--sku 

Os tipos de preço, por exemplo, F1(Gratuito), D1(Compartilhado), B1(Básico Pequeno), B2(Médio Básico), B3(Básico Grande), S1(Standard Small), P1V2(Premium V2 Pequeno), P1V3(Premium V3 Pequeno), P2V3(Premium V3 Médio), P3V3(Premium V3 Grande), I1 (Pequeno Isolado), I2 (Médio Isolado), I3 (Isolado Grande), I1v2 (Isolado V2 Pequeno), I2v2 (Médio V2 Isolado), I3v2 (Isolado V2 Grande), WS1 (Fluxo de Trabalho de Aplicativos Lógicos Standard 1), WS2 (Fluxo de Trabalho de Aplicativos Lógicos Standard 2), WS3 (Fluxo de Trabalho de Aplicativos Lógicos Standard 3).
valores aceitos: B1, B2, B3, D1, F1, FREE, I1, I1v2, I2, I2v2, I3, I3v2, P1V2, P1V3, P2V2, P2V3, P3V2, P3V3, S1, S2, S3, SHARED, WS1, WS2, WS3
_valor padrão: B1_

--is-linux
Hospedar aplicativo Web no trabalho do Linux.

** Deployando nosso codigo [fn:6], [fn:7], [fn:8], [fn:9]

#+begin_src sh name: blkname :exports both :session s1
az webapp deployment user set --user-name <username> --password <password>
#+end_src



Esse comando vai gerar pra gente a url do repositorio remoto pra onde daremos push pra enviar nosso app
#+begin_src sh name: blkname :exports both :session s1
az webapp deployment source config-local-git --name chamadasonline --resource-group rg_chamadasonline
#+end_src


essa e a saida do comando

#+begin_src  js name: blkname  :var x=1  :session s1 :results replace  :exports both :tangle ./subjectdir/tangle/tangled.js  :mkdirp yes
mcr.microsoft.com/azure-cli:latest
{
  "url": "https://SeuUsarioDeDeploay@chamadasonline.scm.azurewebsites.net/chamadasonline.git"
}
#+end_src




* Conectando com o banco
** conectando com um postgres

#+begin_src sh name: blkname :exports both :session s1
#az postgres flexible-server create --resource-group rg_chamadasonline --location westus2
az postgres flexible-server create --resource-group rg_chamadasonline
#+end_src
* Mais...
** az webapp list-runtimes --os Linux
#+begin_example
[
  "DOTNETCORE:7.0",
  "DOTNETCORE:6.0",
  "DOTNETCORE:3.1",
  "NODE:18-lts",
  "NODE:16-lts",
  "NODE:14-lts",
  "PYTHON:3.10",
  "PYTHON:3.9",
  "PYTHON:3.8",
  "PYTHON:3.7",
  "PHP:8.1",
  "PHP:8.0",
  "PHP:7.4",
  "RUBY:2.7",
  "JAVA:17-java17",
  "JAVA:11-java11",
  "JAVA:8-jre8",
  "JBOSSEAP:7-java11",
  "JBOSSEAP:7-java8",
  "TOMCAT:10.0-java17",
  "TOMCAT:10.0-java11",
  "TOMCAT:10.0-jre8",
  "TOMCAT:9.0-java17",
  "TOMCAT:9.0-java11",
  "TOMCAT:9.0-jre8",
  "TOMCAT:8.5-java11",
  "TOMCAT:8.5-jre8",
  "GO:1.19",
  "GO:1.18"
]

#+end_example



* Refs
[fn:1] https://learn.microsoft.com/pt-BR/azure/app-service/quickstart-php?tabs=cli&pivots=platform-linux
[fn:2] https://learn.microsoft.com/pt-br/cli/azure/appservice/plan?view=azure-cli-latest#az-appservice-plan-create
[fn:3] https://learn.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest
[fn:4] https://learn.microsoft.com/en-us/azure/app-service/overview-hosting-plans#how-much-does-my-app-service-plan-cost
[fn:5] https://learn.microsoft.com/pt-br/cli/azure/webapp?view=azure-cli-latest#az_webapp_up
[fn:6] https://learn.microsoft.com/en-us/azure/app-service/deploy-local-git?tabs=cli
[fn:7] https://learn.microsoft.com/en-us/azure/app-service/deploy-local-git?tabs=cli#create-a-git-enabled-app
[fn:8] https://learn.microsoft.com/en-us/azure/app-service/deploy-local-git?tabs=cli#configure-a-deployment-user
[fn:9] https://learn.microsoft.com/en-us/azure/app-service/deploy-configure-credentials?tabs=cli
[fn:10] https://learn.microsoft.com/pt-BR/azure/app-service/configure-language-php?pivots=platform-linux
https://learn.microsoft.com/en-us/azure/app-service/scripts/cli-deploy-local-git
https://learn.microsoft.com/en-us/azure/app-service/overview-hosting-plans
https://learn.microsoft.com/en-us/cli/azure/appservice/plan?view=azure-cli-latest

