
#+title:fzlbpms

* APRESENTACAO
  Este documento ainda é um rascunho com anotações do básico referente
  a um projeto chamado fzlbpms.


* zookeeper
Serviço centralizado gerenciamento de configurações, nomes. Provê sincronização distribuida e serviço de grupos.
Esses serviços são utilizados por aplicações distribuidas



| Definição                         | artigo                                                                                                 |
| Business Process Management (BPM) | Abordagem gerencial focadada em alinhar toda organização às necessidades do cliente[fn:artigo_levi][1] |
| Business Process Management (BPM) | BPM pode ser considerado um tipo de (PAIS) - Process-Aware Information System[fn:artigo_levi][1]       |
| BPM                               | Útil para qualquer tipo de empresa [fn:artigo_levi][2]                                                             |

* Gerenciamento de projeto
  Modelar e Documentar é necessário [fn:artigo_levi]

** Modelar
*** Notações Gráficas
    Petri NetsUML Activity Diagrams, Role Activity Diagrams (RAD), Data Flow Diagrams (DFDs) and State-Transition Diagrams
(STDs) [fn:artigo_levi][5],[6],[4]. 
Notações como  UML and DFDs perspectiva mais informacional do processo
como o fluxo do processo em sí, já as notações RADs and STDs focam
mais no comportamento do processo das atividades. Nenhuma delas é uma
soluçã completa[fn:artigo_levi]


* bpms
** Modelo vs Execução
*** Tradução do modelo para linguagems de execução
    Analístas preferem o modelo com notação visual enquanto Analistas
    de Sistema não só preferem, mas precisam do XML. PRecisa traduzir
    a notação visual para código. BPMN dá um passo nesta direção...

* Referencias
[fn:artigo_levi] Levi - A Workflow Engine Using BPMN 2.0 

