#+Title: Comandos do android
#+Subtitle: Como verificar se os comandos do android estao no path da sua máquina

#+INCLUDE: android_setup_env.org


* Notas Importantes
 adb shell am start -n
 "aulasdeandroid.eteczl.br/eteczl.edu.br.firebaseauth.MainActivity" -a
 android.intent.action.MAIN -c android.intent.category.LAUNCHER -D


sdkmanager --update

avdmanager list avds
[wagner@nsipc163 ExampleLoginApp]$ avdmanager list avd
Parsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/build-tools/28.0.3/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/emulator/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/extras/android/m2repository/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/extras/google/m2repository/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.2/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/patcher/v4/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/platform-tools/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/platforms/android-23/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/platforms/android-24/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/platforms/android-25/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/platforms/android-26/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/platforms/android-27/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/platforms/android-28/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/sources/android-23/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/sources/android-24/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/sources/android-25/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/sources/android-26/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/sources/android-27/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/sources/android-28/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/system-images/android-23/google_apis/x86/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/system-images/android-25/google_apis_playstore/x86/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/system-images/android-26/google_apis_playstore/x86/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/system-images/android-27/google_apis_playstore/x86/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/system-images/android-28/google_apis_playstore/x86/package.xmlParsing /home/wagner/wagnerdocri@gmail.com3/fzlbpms/fzlStudio/integrated/android/androidSdk/tools/package.xmlAvailable Android Virtual Devices:
    Name: Nexus_5X_API_28
  Device: Nexus 5X (Google)
    Path: /home/wagner/.android/avd/Nexus_5X_API_28_1.avd
  Target: Google Play (Google Inc.)
          Based on: Android API 28 Tag/ABI: google_apis_playstore/x86
    Skin: nexus_5x
  Sdcard: 512M
[wagner@nsipc163 ExampleLoginApp]$ 



avdmanager create avd -n test -k "system-images;android-25;google_apis;x86"


pm list users: prints all users on the system.
pm create-user: create a new user with the given USER_NAME,
  printing the new user identifier of the user.

pm remove-user: remove the user with the given USER_IDENTIFIER,
  deleting all data associated with that user

pm get-install-location: returns the current install location.

pm uninstall: removes a package from the system. Options:
    -k: keep the data and cache directories around after package removal.


pm dump: print system state associated with the given PACKAGE.

pm list features: prints all features of the system.

pm list instrumentation: use to list all test packages; optionally
  supply <TARGET-PACKAGE> to list the test packages for a particular
  application.  Options:
    -f: list the .apk file for the test package.


pm list packages: prints all packages, optionally only
  those whose package name contains the text in FILTER.  Options:
    -f: see their associated file.
    -d: filter to only show disbled packages.
    -e: filter to only show enabled packages.
    -s: filter to only show system packages.
    -3: filter to only show third party packages.
    -i: see the installer for the packages.
    -u: also include uninstalled packages.

pm list permission-groups: prints all known permission groups.

pm list permissions: prints all known permissions, optionally only
  those in GROUP.  Options:
    -g: organize by group.
    -f: print all information.
    -s: short summary.
    -d: only list dangerous permissions.
    -u: list only the permissions users will see.


 adb pull storage/3136-6261/videos  ~/wagnerdocri@gmail.com3/Medias/videos

 http://adbshell.com/
 adb shell rm storage/3136-6261/videos/*

 

