#+Title: Lição 04 - Perdão eis a questão

* Plano de Aula
O objetivo geral é ressaltar a importância do perdão, porquanto a parábola de Mateus 18:23-34 nos mostra que Rei, que representa Jesus, perdoou todos os nossos pecados e ele espera que perdoemos nossos irmãos.

A ação inicial contar a parábola e pra isso será realizada um leitura e depois uma releitura para que cada aluno será um personagem da história. Durante a releitura será colocado uma folha de sulfite no aluno dizendo quel seu personagem para que façam a representação do que está sendo lido.

Após a  *compreensão do que a parábola conta*, algumas perguntas serão colocadas para serem respondidas como por exemplo:

Quais são os personagens da história e quem eles representam na vida real?

Qual é a moral dessa história?

O Jogo da Cerdade P.20 Salmo 86:1-6 vai contribuir com a resposta sobre a moral da história, já que vem nos lembrar que *Deus é bondoso e perdoador*

A atividade 2 da página 21 também contribui dizendo, em Mc11:25,26, contribui tb pra dizer que devemos perdoar e essa é uma condição para também alcançar-mos perdão

A atividade 2 p.20 de Mt18:21-22 vai reforçará esse ponto nos exortando a perdoar sempre.

Nesse ponto da aula convém levantar uma questão:

Nós conseguimos entender que estamos diante do Rei e que somos devedores perdoados, afinal estamos na nossa ebd. Mas, pode haver pessoas afirmando que não devem nada a Deus. Pessoas que não estão convencidas do juízo e do pecado. Apesar de estar-mos em irmãos, convem relevar esse ponto e a atividade 3 da pg.22 é ideal para deixar claro que "Se dissermos que não pecamos, fazemo-lo mentiroso, e a sua palavra não está em nós. 1 João 1:10"

Pra não ficar aquela ideia de que o perdao tá sempre garantido e que pecar tudo bem, a atividade 6, de [[https://www.bibliaonline.com.br/acf/ef/1/3-8][Ef1:3-8]], pg.23, vai dar esse equilíbrio deixando claro que o Senhor nos adotou como filhos para *sermos santos e irrepreensíveis*.

As considerações finais serão:

+ "perdão é um ato de fé e de obediência a Deus!" (frase final será da própria revista pg.23)
+ Houve a necessidade do pedido de perdão por parte do devedor
+ O Rei tem seu lado perdoador e seu lado de Justiça
  O Rei tem seu lado perdoador e seu lado justo, do mesmo jeito que perdoou diante do pedido, também condenou diante do ato imcompassivo desse mesmo devedor.
  
+ O jogo da verdade p.21 de Hb9:11-28 relaciona o assunto levando em conta o contexto da velha e da nova aliança valorizando o sangue de Cristo.

* Contação, Encenação e Compreensão da [[https://www-biblestudytools-com.translate.goog/matthew/passage/?q=matthew+18:23-34&_x_tr_sl=auto&_x_tr_tl=pt&_x_tr_hl=pt-BR&_x_tr_pto=wapp][Parabola de Mateus 18:23-34]]
+ Quais são os personagens da parábola e quem eles representam na vida real?
  Rei = Jesus
  Homem que devia muito ao rei = Nós
  Homem que devia para o homem que devia muito ao rei = nosso irmão
  
+ Qual é a moral dessa história?
  (vamos responder utilizando as atividades propostas pela revista)

* Qual a moral dessa história?
** [[https://www-biblegateway-com.translate.goog/passage/?search=Psalm+86:1-6&version=NIV&_x_tr_sl=auto&_x_tr_tl=pt&_x_tr_hl=pt-BR&_x_tr_pto=wapp][(Jogo da Verdade p.20) Salmo86:1-6]]
*O Senhor e bondoso e perdoador*

Apesar de o Senhor ter sido bondoso no início o Senhor não perverteu o juízo e foi literalmente justo no final com o homem que devia muito a ele.


** [[https://www.bibliaonline.com.br/acf/mc/11/25,26][(Atividade 2 p.21) Mc11:25,26]] 
*O Perdão do Senhor é condicional ao nosso perdão*


** ([[https://www.bibliaonline.com.br/acf/mt/18/21,22][Atividade 1 p.20) Mt18:21-22]]
*Devemos perdoar sempre*


** [[https://www.bibliaonline.com.br/acf/cl/3/12-15][(Jogo da Verdade p.20) Cl3:12-15]] 
*Nossa postura deve ser a de perdoar sempre*


** [[https://www.bibliaonline.com.br/acf/ef/1/3-8][(Atividade 6 p.23) Ef:1-3-8]]
*Deus nos escolheu para que fossemos santos e irrepreensíveis* Ef1:4


** [[https://www.bibliaonline.com.br/acf/jo/1/5-10][(Atividade 3 P.22) 1Jo1:5-10]]
*Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo, seu Filho, nos purifica de todo o pecado*


** [[https://www.bibliaonline.com.br/acf/hb/9/11-28][(Jogo da Verdade Pg21) Hb9:11-28]]
O Novo testamento e a Graça

* Considerações finais serão:
+ "perdão é um ato de fé e de obediência a Deus!" (frase final será da própria revista pg.23)
+ Houve a necessidade do pedido de perdão por parte do devedor
+ O Rei tem seu lado perdoador e seu lado de Justiça
  O Rei tem seu lado perdoador e seu lado justo, do mesmo jeito que perdoou diante do pedido, também condenou diante do ato imcompassivo desse mesmo devedor.


* Materiais Disponíveis
https://www.youtube.com/watch?v=Oqnvfv-97ek
https://classes.fabricaebd.org/tudo-a-ver-com-jesus/parabolas-de-jesus/

