SELECT DATEPART(WEEK, GETDATE())

SELECT DATEPART(WEEKDAY, GETDATE())

SELECT DATENAME(WEEKDAY, GETDATE()),  DATENAME (MONTH, GETDATE())

SELECT DAY(GETDATE()),   MONTH(GETDATE()),   YEAR(GETDATE())

SELECT DATEADD(MONTH, 49, GETDATE())

SELECT DATEDIFF (YEAR, '1/1/2009', '1/1/2011')

-- ref: https://www.fabriciolima.net/wp-content/uploads/downloads/2011/05/Fun%C3%A7%C3%B5es-de-Datas.txt
