#+Title: Feliz Ano Novo

Como desejar saude e prosperidade? Deus quer que tenhamos saude e
prosperidade, mas pra conseguir isso nao basta pedir e desejar
muito...  Temos que entender que tanto a saude como a prosperidade e
uma conquista que Deus ajuda a alcancar. 
Como conquistar a saude? Tem que pedir pra Deus sim, mas nao a saude
em si em sim de que maneira eu consigo obter a saude? Ai sim, Deus vai
colocar pessoas no seu caminho, na sua vida, pra te ajudar a descobrir
como conseguir a saude. Sem saude, nao existe prosperidade.
O mesmo com relacao a prosperidade. Deus me da prosperidade!!! Isso
nao funciona. O que funciona, e... Deus, o que eu tenho que fazer pra
conquistar a prosperidade. Ai sim...
Mas mesmo assim, vai precisar mudar coisas em nos pra chegar la...
As vezes nao gostamos e nem temos o habito de fazer algo que Deus
colocou no seu coracoa pra fazer... tipo uma corrida duas vezes na
semana... Vc vai dizer, nao gosto de fazer isso... ai a gente pede pra
Deus.. como que eu faco pra gostar desse negocio? E e assim que a
gente vai moldando nossos habitos...
