#+Title: Redacao: Viver em rede no seculo XXI: Os Limites entre o publico e o privado


O consumo consciente da rede é condicao necessária para obter o melhor
dela e evitar transtornos e sofrimentos.

Usada corretamente, a rede tem tornado as pessoas mais produtivas e
impusionado negocios. Tem melhorado a comunicacoa e proporcionado um
tempo agradavel de entretenimento. A condicao para obter o melhor da
rede, entretanto, é seguir boas praticas de uso, como por exemplo: nao publicar endereco residencial, localizacao atual,
e nao ficar o dia inteiro nas redes, dentre outras.

Infelizmente o mau uso da rede e
a falta de percepcao dos usuarios entre o publico e o privado tem
alimentado de informacoes pessoas mal intensionadas para planejarem sequestros, assaltos, assinatos de
reputacões, propagação de "fake news", dentre outras vis acoes.

Sendo assim é mister lembrar algumas práticas de bom convívio na
rede como a checagem da veracidade das informacoes, moderação ao
publicar ou compartilhar conteúdos tanto pessoais como de outras
pessoas, nao substituir os relacionamentos pessoais pelos mantidos
pela rede, controlar o tempo na rede. Por esse motivo autoridades tem
legislado sobre fake news e trazido a público o diálogo sobre  a
necessidade do uso consciente da rede embora ainda haja necessidade de
ampliar acoes nesse sentido.

Transpassar os limites do publico e do privado é consequencia do uso
não consciente da rede. Refletir sobre o assunto é importante para
melhorar a percepcao sobre os limites do público e o privado
promovendo assim um desfrutar do melhor da rede.
