#+Title: Amalequitas

anots

atacaram israel em sua saida do Egito, mas ataca por trás, os mais
fracos.

descententes do proprio neto de abraao.. ou seja eram da linhagem de
abraao

Deus jurou aniquiliar os amalequitas

Gn 36:12 Esau tinha um filho chamado Elifas, que por sua vez, tinha
uma concumbina chamada Timina, da qual teve Amaleque.

Amaleque era neto de Esaú, bisneto de Isaque. Não eram estrangeiros. O
sangue dos patriarcas corria em suas veias. Eram da linhagem de Jacó.

Amaleque era um dos líderes tribais de Edom. V16 (Corá, Data e
Amaleque)

Amaleque se tornou um líder

Os Amalequitas migraram para o sul, deserto de Neguebe, Sinai. Local
bruto.. tipo dunas..

Eles memorizaram a localização de cada local onde havia água. Um
conhecimento muito relevante

Estavam sempre em movimento de acordo com as suas provisões. Essa era
uma vantagem que povos fixos não tinham.






* Refs
[fn:1] Video: Quem eram os amalequitas na Bíblia? A origem do povo de Amaleque - https://www.youtube.com/watch?v=40pz7mfEjTQ
