#+Title: 7 Maximas Hermeticas

* Introducao
  Uma maneira de pensar a o mundo.
  
* 7 Maximas Hermeticas
  + Mentalismo
    Tudo e mente, nao ha acaso. O universo nasce de um plano mental e
    seu universo tambem. Por isso o que cada um pensa e fundamental.
  + Correspondencia
    O que esta acima e como o que esta abaixo. A ideia e que as coisas
    funcionam de maneira analoga em quaisquer planos que o universo possui: no macro e no
    micro, interno e externo, etc... quais esses planos? pois e... 
  + Vibracao
    Nada esta parado, tudo vibra
  + Polaridade
    Tudo e duplo, tudo tem um par oposto. O quente e o frio
  + Ritmo
    Ritmo e a compensacao da vibracao e polaridade. A abstracao do
    pendulo relativo as coisas da vida... so que a intensidade do
    pendulo pra um lado pode (na vida) refletir, na mesma intensidade,
    do lado oposto.
  + Causa e efeito
    Toda causa tem seu efeito todo efeito tem sua causa ainda que a
    gente nao tenha detectado ou compreendido um deles.
  + Genero
    Genero vem da palavra gerar (generare) que gera tudo. tudo tem o
    principio feminino e masculino. A questao de sexualidade e
    aplicavel apenas qdo se trata do corpo do ser humano ou do
    animal, mas quando se trata de todo o resto, tudo tem o principio
    feminino e masculino. 

    A criacao de algo esta ligado a esse principio e tambem ele ligado
    aos demais principios.
    


