#+Title: Palavra

* Por que Deus endureceu o coração do faraó da época de Moisés
  Porque a paga pelo coração duro de matar as crianças foi o
  endurecimento do seu próprio coração.

  Não há condenação maior que o endurecimento do coração.

  Foi algo assim que aconteceu com Caim quando Deus diz pra ele que se
  ele não dominasse o pecado o desejo dele seria para ele mesmo.

  De tudo quanto se deve aguardar, guarde o seu coração. Não deixe
  entrar qualquer coisa. Entregue seu coração ao Senhor.

* O Sangue de Jesus
  Tem a única função de salvar da justa mão de Deus contra nosso
  coração duro.

  Justa é uma palavra que precisa ser entendida, pois a justiça de
  Deus é quase sempre confundida com maldade de Deus.

  Deus é justo e nós não. Essa é a chave interpretativa. O julgamento
  dele em relação a nós é perfeito e o nosso julgamento em relação a
  ele é indevido. Não se pode Julgar à Deus, nem tampouco sua justiça

  Zípora circucidou Gerson e melou de sangue a Moisés e por isso
  Moisés não foi morto por Deus.

  No Egito o Anjo da Morte não visitou as casas cujos humbrais da casa
  estavam lambuzados de sangue.

  Jesus nos cobre com seu sangue. O Sangue de Jesus tem poder pra
  livrar da justiça de Deus.
  
  
