#+SETUPFILE: ../etc/org_mode_SETUPFILE.org
#+TITLE: Plano de Aula - Movimentos do Mouse

* TEMA 
  Movimentação do Mouse


* Duração
  1h

* CONTEXTO e INDICAÇÃO
  Movimentos do Mouse
  Parece algo desnecessário dizer movimentar o cursor do mouse pra esquerda e pra direita. Mas durante as aulas observou-se que boa parte dos idosos movimentam o mouse pra esquerda de forma incorreta, ou seja, ao invés de transportar o mouse 'de lado' como 'carangueijo' eles não transportam o mouse e sim giram a ponta do mouse pra esquerda. Essa movimentação não resulta na movimentação pra esquerda como se esperava e ele não entende o porquê.
  Outra dificuldade dos alunos é que, as vezes, quando precisam movimentar o mouse para baixo, ocorre que não tem mais espaço pra abaixar o mouse no mousepad, ou seja, não tem espaço físico no mousepad pra abaixar o mouse, entretanto, o cursos do mouse na tela ainda precisaria ser abaixado ainda mais. O aluno não tem a habilidade de levantar o mouse do mousepad, recolocar o mouse em uma posição um pouco mais acima do mousepad e após esse movimento, realizar novamente o movimento de abaixar o cursor do mouse e chegar então onde ele precisa na tela do computador.
  Esta lição é indicada para alunos com essas dificuldades.

* OBJETIVO GERAL
  Demostrar e Treinar Movimentação Lateral, para cima e para baixo do Mouse


* CONTEÚDO PROGRAMÁTICO
Apresentação breve do mouse e demostração de seus movimentos para cima, para baixo, para esquerda e para direita.



* Recursos, Metodologia
Material didático em anexo com imagens do mouse e explicação escrita e ilustrada dos movimentos do mouse.
Jogos e Explicação do jogo para exercícios de movimentação do mouse.


* Avaliação


* REFERÊNCIAS





  Introdução ao Git e Github
