#+Title: Adm Rascunho

* Consultar saldo do PASEP
  Url:
  http://www.bb.com.br/pbb/pagina-inicial/setor-publico/governo-federal/gestao/gestao-de-recursos/pagamento-de-ordens-bancarias,-salarios-e-beneficios/pasep#/


* PIS
PIS é a sigla para Programa de Integração Social, uma contribuição tributária de caráter social, que tem como objetivo financiar o pagamento do seguro-desemprego, abono e participação na receita dos órgãos e entidades, tanto para os trabalhadores de empresas públicas, como privadas.

* NIS [fn:significado-nis]
NIS significa Número de Identificação Social. É um número de cadastro
atribuído pela Caixa Econômica Federal às pessoas que serão
beneficiadas por algum projeto social e ainda não possuem cadastro no
PIS (Programa de Integração Social)

* NIS x NIT[fn:significado-nis]
Diferença entre NIS e NIT

NIT significa Número de Identificação do Trabalhador. É um número obtido diretamente na Previdência Social (INSS). O NIT é o número de identificação do trabalhador autônomo, ou seja, aquele que nunca trabalhou com carteira assinada.

Um contribuinte individual, com NIT, apenas recolhe no INSS (Instituto Nacional do Seguro Social).

Se uma empresa contratar um trabalhador que possua apenas o NIT, deverá fazer o cadastro do funcionário no PIS.
  

* Referencias
[fn:significado-nis] https://www.significados.com.br/nis/
[fn:significado-pis] https://www.significados.com.br/pis/
