* IDENTIFICAÇÃO:
NOME DO PROJETO: Autonomia e Independencia do Idoso através do trabalho
DIRETRIZ: Envelhecimento Ativo

* PRESENTAÇÃO DA ORGANIZAÇÃO:
Nome: (razão social)
CNPJ n°:
Banco: Agência: C/C Geral:
Registro no COMAS nº: Validade do Registro:
Endereço: N°: Complemento:
Bairro: Cidade: Estado: CEP:
Email: Endereço Internet: (site oficial)
Nome - Responsável pelo projeto:
Telefone
fixo: Celular: Email: (está será a principal forma de contato entre o CMDCA e a
OSC)
Nome - Responsável Legal da Organização:
Telefone
fixo: Celular: Email: (está será a principal forma de contato entre o CMDCA e a
OSC)

* APRESENTAÇÃO DO PROJETO:
Local/Endereço e Região de Atuação do Projeto: (indicar o endereço do (s) imóvel
(is) onde se dará a realização - é essencial para análise de classificação. Sem este
item preenchido, não é possível identificar o local de atuação e, com isso, pontuá-lo.)
Objetivo Geral: (Descrição dos objetivos gerais e específicos de forma a identificar
como o planejamento pretende garantir sua efetivação. Exemplificando: “Estimular as
competências linguísticas orais dos beneficiários, por meio de um ambiente seguro e
mediado, em que possam compartilhar e aprofundar discursivamente suas
experiências de vida e aprofundar suas capacidades de absorver conteúdos artísticos,
reconhecendo e valorizando traços de sua cultura”)

* Objetivos Gerais:
Direitos da cidadania viabilizando sua participação na comunidade, defendendo sua dignidade, bem-estar e o direito à vida (PNI)Art3 [fn:3]
O idoso tem direito ao exercício de
atividade profissional, respeitadas suas condições
físicas, intelectuais e psíquicas.

* Objetivos Específicos
* Ações Fim
Conscientização da sociedade sobre o processo de envelhecimento (PNI Art3 Inciso 4)

* Ações Meio
** promover
+ formas alternativas de participação e convívio do idoso
  Eventos para os idosos para promoção da convivência e também na área de negócios
  
+ Conscientização e promoção das formas representativas de apoio ao idoso
   na formulação, implementação e avaliação das políticas, planos, programas e projetos a serem desenvolvidos;
   promover simpósios, seminários e encontros específicos;
   
+ Capacitações e Demais ações educacionais
  capacitação e reciclagem dos recursos humanos gerontologica e na prestação de serviços; PIN Art3 VII

+ Captação de dados para apoio a estudos sobre envelhecimento

Parágrafo único. É vedada a permanência de portadores de doenças que necessitem de assistência médica ou de enfermagem permanente em instituições asilares de caráter social.Ctlo4[fn:4]

 preparação dos trabalhadores para a apo-
sentadoria, com antecedência mínima de 1 (um)
19
ano, por meio de estímulo a novos projetos sociais,
conforme seus interesses, e de esclarecimento sobre
os direitos sociais e de cidadania (CploIV[fn:4]

* Justificativa
Considerando que "as diferenças econômicas, sociais, regionais e, particularmente, as contradições entre o meio rural e o urbano do Brasil deverão ser observadas pelos poderes públicos e pela sociedade em geral, na aplicação desta lei."PNI Art4 Inc. IV[fn:3]"
Considerando que a fonte de renda urbana depende principalmente dou do trabalho ou da atividade autônoma, este projeto propoe contribuir com o poder público proporcionando aos idosos essa alternativa de trabalho autonomo através de parceria

profissionalização especializada para os idosos, aproveitando seus potenciais e habilidades para atividades regulares e remuneradas[fn:4]

Colaborar com poder público no alinhamento com recomendações de orgãos mundiais, mais específicamente:
+ políticas públicas [fn:5]
+ Conhecimento, proposicções de ações sociedade gerontolia das américas[fn:6]
+ Fragilidade do idoso
  Há estudos de harvard que sugerem haver trabalho idoso não remunerado ou remunerado injustamente, em especial em relação ao genero feminino[fn:7]
  


* Conceituando Idoso
A política nacional do idoso (PNI), , e o estatuto do Idoso,Lei nº 10.741,de 1º de outubro de 2003, define Idoso pessoas com 60 anos ou mais. Já a Organização Mundial da Saúde (OMS) (2002) define o idoso a partir da idade cronológica, portanto, idosa é aquela pessoa com 60 anos ou mais, em países em desenvolvimento e com 65 anos ou mais em países desenvolvidos. É importante reconhecer que a idade cronológica não é um marcador preciso para as mudanças que acompanham o envelhecimento. Existem diferenças significativas relacionadas ao estado de saúde, participação e níveis de independência entre pessoas que possuem a mesma idade (Brasil, 2005).
Para efeitos da lei Lei nº8. 842, de 4 de janeiro de 1994 que institui a PNI - Política Nacional do Idoso, considera-se idosa a pessoa maior de sessenta anos de idade.[fn:3]
* Conjuntura economica e social
É consenso constatar que a população idosa tem maior expectativa de vida e permanece socialmente mais ativo por mais tempo.[fn:1]
As organizações e órgãos públicos já trabalham ações dentro dessa perspectiva, e são muitos os exemplos práticos: "Oficina para Idoso" do procon[fn:1];


Envelhecimento bem-sucedido e capacidade funcional
Violência contra idosos (Maus Tratos e violência Financeira)

* Fatores relevantes para Empreendedorismo em Idosos
capacidade funcional para a atividade


* Benefícios do Programa
** À saúde
Prolongar a vída produtiva (Gerontologo, Enfermeiro do Trabalho), por exemplo: prebióticos, probióticos e simbióticos em
adultos e idosos

Ambiente físico e acessibilidade espacial


* Profissionais fixos
+ Gerontologo
  Planejamento e direçao:
  a) na promoção de eventos de convívio e ações para envelhecimento ativo
  b) articulação e parceria para na coleta, curadoria, e análise de dados para efeitos de pesquisas, levantamentos, publicações na área do envelhecimento, em particular sobre a situação social dentro do do contexto do empreendedorismo.
  c) promover a capacitação de recursos para atendimento ao idoso;
  e) Empoderamento  Universidade Aberta para Terceira Idade para manter ativo e capacidade funcional
  f) articular com outras áreas da saúde (geriátrica, nutricção , etcc) para prevenção e manutenção da saúde
  g) Articular com Administrador, Enfermeiro do Trabalho  aspectos específicos da gerontologia como capacidade funcional e a área de atuação profissional do idoso bem como riscos e comorbidades para potencializar envelhecimento ativo dentro do contexto da prática profissional do idoso. Articular com Assistente social prevenção contra violência contra o idoso em particular a violência financeira. 

O idoso tem direito ao exercício de
atividade profissional, respeitadas suas condições
físicas, intelectuais e psíquicas.

+ Assistente Social
  - Suporte, conscientização e inserção do idoso nas diversas alternativas para atuação do idoso em suas formas representativas
  - Acesso a justica atendimento
  - Observar e dar suporte ao idoso em aspectos especificos citados no estatudo do idoso:
    trabalho ou emprego que impor limite de idade e que impede participação do idoso

  - Articulação com políticas publicas
    

 preparação dos trabalhadores para a apo-
sentadoria, com antecedência mínima de 1 (um)
19
ano, por meio de estímulo a novos projetos sociais,
conforme seus interesses, e de esclarecimento sobre
os direitos sociais e de cidadania

para concursos, ressalvados os casos em que a
natureza do cargo o exigir.
+ Administrador
  Planejar e dirigir as ações de capacitação do idoso em sua área de atividade articulando com recursos como Universidade Aberta para Terceira Idade
  Planejamento e direção nas ações de suporte às ações empreendedoras bem como articulação de parcerias capazes de catalizar o alcance desses objetivos como por exemplo: sebrae.
  Suporte a legalização do negócio do idoso, como por exemplo "Micro empreendedor"
  adequar currículos, metodologias e material didático aos programas educacionais destinados ao idoso; sobre empreendedorismo
  Dar capacitação: profissionalização especializada para os idosos, aproveitando seus potenciais e habilidades para atividades regulares e remuneradas[fn:4]

Articular com empresas onde estímulo às empresas privadas para ad-
missão de idosos ao trabalho.

+ Enfermeiro do Trabalho
  Planejamento, supervisão e suporte âs ações operacionais do trabalho de cada negócio iniciado pelo idoso
+ Profissional de Informática
  Inclusão Digital 
  Atuar na proposição, criar, conscientização de  conteúdos digitais adequados às condições do idoso
  Suporte operacional de informátiva como criação de site, formulários de pesquisas, gestão de dados para tomada de decisões e pesquisas bem como apoio de informática aos processos administrativos e operacionais 
  Suporte ao idoso no consumo de conteúdos educacioanis na modalidades de ensino à distância

* Refs
[fn:1] https://www.procon.sp.gov.br/epdc/#epdc_inscricoesabertas
[fn:2] https://sbgg.org.br/wp-content/uploads/2014/10/2014-1.pdf
[fn:3] http://www.planalto.gov.br/ccivil_03/leis/l8842.htm
[fn:4] https://conselho.saude.gov.br/biblioteca/livros/estatuto_idoso2edicao.pdf
[fn:5] https://www.worldpolicycenter.org/topics/aging/policies
[fn:6] https://www.geron.org/about-us/our-vision-mission-and-values/what-is-gerontology
[fn:7] https://www.hks.harvard.edu/sites/default/files/centers/cid/files/publications/CID_Wiener_Inequality%20Award%20Research/Rose%20Khattar%20Report%20(1-A).pdf
