#+SETUPFILE: ../etc/org_mode_SETUPFILE.org
#+TITLE: INSALUBRIDADE E PERICULOSIDADE

Explique a diferença entre insalubridade e periculosidade
O funcionário foi demitido por justa causa e a empresa anotou sua
   demissão na CTPS mencionado isso. O empregador fez correto porque a
   anotação na carteira de trabalho foi realizada condizente ao que
   realmente ocorreu, ou o empregador não deveria ter mencionado isso
   na CTPS?
   O empregador não pode fazer anotações desabonadoras na CTPS de seus empregados. 
   Entende-se por desabonadora a informação caluniosa, discriminatória
   e que não diga respeito  unicamente  aos  dados  do  Contrato  de
   Trabalho  e  que  possa  dificultar  ao  trabalhador  conseguir
   novos  empregos,  como,  por  exemplo,  ocorrência  de  dispensa
   por   justa causa.[fn:ref2]pg15


1 - TRT 9ª 2013 - FCC - Técnico Judiciário - Área Administrativa
O trabalho em condições de periculosidade assegura ao empregado um adicional sobre o salário sem os acréscimos resultantes de gratificações, prêmios ou participações nos lucros da empresa. O percentual do adicional de periculosidade é de
10%.
50%.
20%.
40%.
30%.


2- TRT 9ª 2013 - FCC - Analista Judiciário - Área Judiciária
Considere as proposições:
I. Atividades ou operações insalubres são aquelas que, por sua natureza, condições ou métodos de trabalho, exponham os empregados a agentes nocivos à saúde, acima dos limites de tolerância fixados em razão da natureza e da intensidade do agente e do tempo de exposição aos seus efeitos.
II. A eliminação ou neutralização da insalubridade ocorrerá com a adoção de medidas que conservem o ambiente de trabalho dentro dos limites de tolerância e com a utilização pelo trabalhador de EPI's que diminuam a intensidade do agente agressivo a limites de tolerância.
III. O trabalho em condições de periculosidade assegura ao empregado um adicional de 30% (trinta por cento) sobre o salário, com os acréscimos resultantes de gratificações, prêmios ou participações nos lucros da empresa.
IV. A caracterização e a classificação da insalubridade e da periculosidade far-se-ão através de perícias, ficando a primeira a cargo de Médico do Trabalho e a segunda a cargo de Engenheiro do Trabalho, registrado no Ministério do Trabalho.
V. O adicional de insalubridade e o adicional de periculosidade incorporam-se ao salário do empregado, não podendo deixar de ser pagos mesmo que tenha havido a cessação do risco à saúde ou a integridade física do mesmo.

Está correto APENAS o que se afirma em
III, IV e V.
II, III e V.
I e II.
II e IV.
I, II e V.


3 - TRT 1ª 2013 - FCC - Analista Judiciário - Área Administrativa

Em relação às atividades insalubres ou perigosas é correto que
o trabalho em condições perigosas assegura ao empregado um adicional de vinte por cento sobre o salário base.
o trabalho em condições insalubres assegura ao empregado um adicional de 10%, 30% e 40% do salário mínimo, segundo se classifiquem nos graus mínimo, médio e máximo.
o direito do empregado ao adicional de insalubridade ou de periculosidade cessará com a eliminação do risco à sua saúde ou integridade física.
a caracterização e a classificação da insalubridade e da periculosidade, segundo as normas do Ministério do Trabalho, far-se-ão através de perícia, sendo a de insalubridade realizada por médico do trabalho e a de periculosidade por engenheiro do trabalho.
o empregado que trabalhe em condições perigosas e insalubres receberá ao mesmo tempo os dois adicionais.



1-E
2-C
3-C

http://www.mapadaprova.com.br/questoes/de/direito-do-trabalho/normas-de-medicina-e-seguranca-do-trabalho/atividades-insalubres-e-perigosas#

* referências
[fn:ref1] http://www.ocuidador.com.br/imgs/utilidades/trabalhador-5267d62168d8a.pdf
[fn:ref2 ] http://www.cfa.org.br/servicos/publicacoes/cfa_cartilha_trabalho.pdf
